config/routes.rb
Rails.application.routes.draw do

  root'access#login'
  get 'gallery/index'
  get 'video/index'
  get 'admin', :to => 'access#menu'
  get 'access/menu'

  # get 'access/login'

  post 'access/attempt_login'
  get 'access/logout'

  get 'experiments/tts'
  post 'experiments/tts'
  get 'demo/hellos'
 
  #get ':controller(/:action(:id))'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	has_secure_password

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates_presence_of :first_name
	validates_length_of :first_name, :maximum => 25
	validates_presence_of :second_name
	validates_length_of :second_name, :maximum => 50
	validates_presence_of :username
	validates_length_of :username, :within => 8..25
	validates_uniqueness_of :username
	validates_presence_of :email 
	validates_length_of :email, :maximum => 100
	validates_format_of :email, :with => EMAIL_REGEX
	validates_confirmation_of :email
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  def menu
  	#text + links
  end

  def login
  	#form
  end
  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user = AdminUser.where(:username => params[:username]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])
  		end	

  		if authorized_user
  			session[:user_id] = authorized_user.id
  			flash[:notice] = "logged"
  			redirect_to(admin_path)
  		else
  			flash.now[:notice] = "wrong"
  			render('login')
  		end
  end
  end

  def logout
  	session[:user_id] = nil
  	flash[:notice] = 'Loogged out'
  	redirect_to(access_login_path)

  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
skip_before_action :verify_authenticity_token

  private

  def confirm_logged_in
  	unless session[:user_id]
  		flash[:notice] = "Please log in."
  		redirect_to(access_login_path)
   	end
 	end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
layout false
  def index

  end
  def hellos

  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
 layout 'admin'
  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  def tts
  	 #  unless params[:request].nil?
    #   if check.valid?
    #     conversion
    #   else
    #     error_info
    #   end
    # end
  end

 

  def conversion
    audio_format = TtsConversion.index(client, synthesis_input, voice, audio, params[:codec])
    success_info(audio_format)
  end

  def client
    Google::Cloud::TextToSpeech.text_to_speech
  end

  def synthesis_input
    { params[:text_or_ssml] => params[:request] }
  end

  def voice
    { language_code: params[:lang], name: params[:voicename] }
  end

  def audio
    { audio_encoding: params[:codec] }
  end

  def check
    # Validation.new(form_params)
  end

  def success_info(audio_format)
    flash[:notice] = "<a href='/output/output.#{audio_format}' download>Download #{audio_format}</a>".html_safe
  end

  def error_info
    flash[:error] = 'Invalid request format'
  end

  private

  def form_params
    params.permit(:request)
end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
layout 'admin'
  def index
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
layout 'admin'
  def index
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="login">
	<%= form_tag(access_attempt_login_path, :method =>:post) do %>
		<table>
			<tr>
				<td><%= label_tag(:username) %></td>
				<td><%= text_field_tag(:username, params[:username]) %></td>
			</tr>
			<tr>
				<td><%= label_tag(:password) %></td>
				<td><%= password_field_tag(:password) %></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td><%= submit_tag("Log In") %></td>
			</tr>
		</table>
	<% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Menu" %>
<div class="menu">
<h2>Menu</h2>
<div class="identity">Logged in as:</div>
<nav class="menu">
	<li><%= link_to("Google", experiments_tts_path)%>
	<li><%= link_to("Gallery", gallery_index_path)%>
	<li><%= link_to("Video", video_index_path)%>
	<li><%= link_to("Logout", access_logout_path)%>
		
	</li>
</nav>
</div>

app/views/demo/hellos.html.erb
<h1>Hell</h1>
<%= link_to('ENDEX', {:action =>'index'}) %>

app/views/demo/index.html.erb
<h1>will be the welcome page</h1>
<a href="/demo/hellos">to hell</a></br>
<%= link_to('TO HELL',{:action => 'hellos'})%> </br>

app/views/experiments/tts.html.erb
<div class="container"></div>

<%= simple_form_for :user, remote: true, :url => '/experiments/tts', :method => :post do |f| %>
 <%= f.error_notification %>
  <%= f.input :request, placeholder: "Enter your text: ", :as => :text, input_html: { :style=> 'width: 70%;', :rows => 10, id: "body-field", name: "request", include_blank: false, required: true} %>

<div class="chained-selects">
   <select required id="select-1" name="lang">
      <option value="" selected>Choose language/locale</option>
      <option value="en-US">English (United States)</option>
      <option value="ru-RU">Русский (Россия)</option>on>
   </select>
   <select required id="select-2" disabled>
      <option value="" selected>Choose voice type</option>
   </select>
   <select required id="select-3" name="voicename" disabled>
      <option value="" selected>Choose voice name</option>
   </select>
</div>
<div class="radio-button">
   <div class="custom-control custom-radio custom-control-inline">
      <input type="radio" class="custom-control-input" id="MP3" value="MP3" name="codec" checked="checked">
      <label class="custom-control-label" for="MP3">MP3</label>
   </div>
   <div class="custom-control custom-radio custom-control-inline">
      <input type="radio" class="custom-control-input" id="WAV" value="LINEAR16" name="codec">
      <label class="custom-control-label" for="WAV">WAV</label>
   </div>

</div>
<div id="btnSubmit" type="submit" class="btn btn-light">
   <%= f.button :submit, 'Send' %>
   <% end %>
</div>
</form>

app/views/gallery/index.html.erb
<h1>Gallery#index</h1>
<p>Find me in app/views/gallery/index.html.erb</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleProject</title>
  </head>

  <body>
  <% if !flash[:notice].blank? %>
  	<div class="notice">
  <%= flash[:notice] %>
  </div>
  <% end %>
    <%= yield %>
   <div><%= link_to("Back to menu", admin_path) %> </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/video/index.html.erb
<h1>Video#index</h1>
<p>Find me in app/views/video/index.html.erb</p>